server:
  servlet:
    jsp:
      init-parameters:
        development: 'true'
  port: 7070

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    password: tmdlswo123
    driver-class-name: oracle.jdbc.OracleDriver
    username: togetherTeam
    url: jdbc:oracle:thin:@project-db-stu.ddns.net:1524/xe
  thymeleaf:
    enabled: 'false'
  devtools:
    livereload:
      enabled: true
    
mybatis:
  mapper-locations: mybatis/mapper/**/*.xml
  configuration:
    jdbc-type-for-null: 'NULL'
    cache-enabled: 'false'